<?php

namespace SiteBundle\Repository;

/**
 * EmailEtapeInscription_PieceJointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailEtapeInscription_PieceJointeRepository extends \Doctrine\ORM\EntityRepository
{
}
