<?php

namespace SiteBundle\Repository;

/**
 * EmailEtapeInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailEtapeInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
