<?php

namespace SiteBundle\Repository;

/**
 * EtapeInscriptionEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeInscriptionEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
