<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionAutreEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionAutreEtablissementRepository extends EntityRepository
{
}
