<?php

namespace SiteBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
    public function findOffresByData($parametres)
    {
        $query = $this->_em->createQueryBuilder();
        $query
            ->select('o')
            ->from($this->_entityName, 'o')
            ->leftJoin('SiteBundle:Entreprise', 'e', 'WITH', 'o.Entreprise = e.id')
            ->leftJoin('SiteBundle:Adresse', 'a', 'WITH', 'e.Adresse = a.id')
            ->where(
                $query->expr()->orX(
                    $query->expr()->like('o.titre', ':motsCles'),
                    $query->expr()->like('o.sujet', ':motsCles')
                )
            )->setParameter('motsCles', '%' . $parametres['motsCles'] . '%');
        $query
            ->andWhere(
                $query->expr()->like('a.commune', ':ville')
            )->setParameter('ville', '%' . $parametres['ville'] . '%');
        $query
            ->andWhere(
                $query->expr()->like('a.codePostal', ':dpt')
            )->setParameter('dpt', $parametres['dpt'] . '%');
        if (count($parametres['licence']) > 0)
            $query
                ->andWhere(
                    $query->expr()->in('o.licenceConcerne', $parametres['licence'])
                );
        $query->andWhere(
            $query->expr()->eq('o.etatOffre', ':etatOffre')
        )->setParameter('etatOffre', 'En ligne');
        return $query->getQuery()->getResult();
    }

}


