<?php

namespace SiteBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;


/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
     

}


