<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParentEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentEtudiantRepository extends EntityRepository
{
}
