# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
            our_db_provider:
                entity:
                    class: SiteBundle:User
                    property: username

    encoders:
            SiteBundle\Entity\User:
                algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                success_handler: redirect.after.login
            logout:
                path: logout
            remember_me:
                secret:   '%secret%'

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/responsable, roles: ROLE_ADMIN }
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }
        - { path: ^/entreprise, roles: ROLE_ENTREPRISE }