# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    redirect.after.login:
        class: SiteBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]
    app.twig_extension:
            class: SiteBundle\Twig\TwigExtension
            public: false
            tags:
                - { name: twig.extension }
